name: CICD
on:
  - push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: web-design-system/server
      baseImage: cloud-cli/node:latest
      type: node
