name: CICD
on:
  push:
    branches:
      - main
jobs:
  release:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: web-design-system/server
      type: node